version: "2.2"

services:

  mariadb:
    image: docker.dev.shoogoome.com/firehydrant/mariadb:1.0
    container_name: fire-hydrant-mariadb
    volumes:
      - ${FIRE_HYDRANT_MYSQL_WORK_DIR}:/var/lib/mysql
      - ${FIRE_HYDRANT_MYSQL_LOG_DIR}:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${FIRE_HYDRANT_MYSQL_ROOT_PASSWORD}

  pma:
    image: docker.dev.shoogoome.com/firehydrant/phpmyadmin:1.0
    container_name: fire-hydrant-pma
    links:
      - mariadb:db
    depends_on:
      - mariadb

  redis:
    image: docker.dev.shoogoome.com/firehydrant/redis:1.0
    container_name: fire-hydrant-redis
    volumes:
      - ${FIRE_HYDRANT_REDIS_WORK_DIR}:/data
    ports:
      - "6379:6379"

  rabbitmq:
    image: docker.dev.shoogoome.com/firehydrant/rabbitmq:1.0
    container_name: fire-hydrant-rabbitmq
    hostname: firehydrant
    volumes:
      - ${FIRE_HYDRANT_RABBITMQ_WORK_DIR}:/var/lib/rabbitmq/mnesia
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=${FIRE_HYDRANT_RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${FIRE_HYDRANT_RABBITMQ_ROOT_PASSWORD}

  server:
    image: docker.dev.shoogoome.com/firehydrant/server:1.0
    container_name: fire-hydrant-server
    depends_on:
      - mariadb
      - redis
      - rabbitmq
    links:
      - mariadb:mysqldb
      - redis:redis
      - rabbitmq:rabbitmq
    volumes:
      - ${FIRE_HYDRANT_SERVER_WORK_DIR}:/firehydrant
      - ${FIRE_HYDRANT_SERVER_LOG_DIR}:/logs
      - ${FIRE_HYDRANT_SERVER_CONF_DIR}:/firehydrant/config.yml

  web:
    image: nginx:1.13
    container_name: fire-hyrant-web
    depends_on:
      - pma
      - rabbitmq
      - server
    links:
      - pma:pma
      - rabbitmq:rabbitmq
      - server:server
    volumes:
      - ${FIRE_HYDRANT_WEB_CONF_DIR}:/etc/nginx/conf.d/firehydrant.conf
    ports:
      - "80:80"