# Generated by Django 2.1.2 on 2019-08-01 10:40

import common.core.dao.time_stamp
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcesMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mime', models.CharField(max_length=100)),
                ('size', models.BigIntegerField(default=0)),
                ('hash', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('create_time', common.core.dao.time_stamp.TimeStampField(default=0)),
            ],
            options={
                'verbose_name_plural': '资源元数据记录表',
                'verbose_name': '资源元数据记录',
            },
        ),
    ]
