# Generated by Django 2.0.2 on 2019-07-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='config',
            field=models.TextField(default='{"publish_start_time": 0, "publish_end_time": 0, "implement": {"staged": 0, "stage": {"stage_start_time": 0, "stage_end_time": 0, "title": "", "describe": ""}}}'),
        ),
    ]
