# Generated by Django 2.0.2 on 2019-07-14 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20190711_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.TaskClassification')),
            ],
            options={
                'verbose_name': '任务分类',
                'verbose_name_plural': '任务分类表',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='commission',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='task',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.TaskClassification'),
        ),
    ]
