# Generated by Django 2.1.2 on 2019-07-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20190714_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='config',
            field=models.TextField(default='{"publish_end_time": 0, "implement": {"stage": {"stage_end_time": 0, "describe": "", "title": "", "stage_start_time": 0}, "staged": 0}, "publish_start_time": 0}'),
        ),
    ]
