# Generated by Django 2.1.2 on 2019-07-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20190719_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='config',
            field=models.TextField(default='{"publish_end_time": 0, "publish_start_time": 0, "implement": {"staged": 0, "stage": {"describe": "", "stage_start_time": 0, "title": "", "stage_end_time": 0}}}'),
        ),
    ]
