# Generated by Django 2.1.2 on 2019-07-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20190720_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='config',
            field=models.TextField(default='{"publish_end_time": 0, "implement": {"staged": 0, "stage": {"stage_end_time": 0, "describe": "", "stage_start_time": 0, "title": ""}}, "publish_start_time": 0}'),
        ),
    ]
