# Generated by Django 2.1.2 on 2019-08-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20190720_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskreport',
            name='resource_links',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='config',
            field=models.TextField(default='{"implement": {"staged": 0, "stage": {"stage_end_time": 0, "title": "", "describe": "", "stage_start_time": 0}}, "publish_start_time": 0, "publish_end_time": 0}'),
        ),
    ]
