# Generated by Django 2.1.2 on 2019-08-01 10:48

import common.core.dao.time_stamp
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('account', '0003_accountexhibition'),
        ('task', '0010_auto_20190801_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('create_time', common.core.dao.time_stamp.TimeStampField(default=0)),
                ('update_time', common.core.dao.time_stamp.TimeStampField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
                ('exhibition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AccountExhibition')),
            ],
            options={
                'verbose_name': '任务申请',
                'verbose_name_plural': '任务申请表',
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='resource_links',
        ),
        migrations.AddField(
            model_name='task',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.ResourcesMeta'),
        ),
        migrations.AlterField(
            model_name='task',
            name='config',
            field=models.TextField(default='{"publish_end_time": 0, "publish_start_time": 0, "implement": {"staged": 0, "stage": {"stage_start_time": 0, "stage_end_time": 0, "title": "", "describe": ""}}}'),
        ),
        migrations.AddField(
            model_name='taskapply',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
    ]
