# Generated by Django 2.1.2 on 2019-08-01 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_accountexhibition'),
        ('resources', '0001_initial'),
        ('task', '0011_auto_20190801_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskreport',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='taskreport',
            name='workers',
        ),
        migrations.AddField(
            model_name='task',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_leader', to='account.Account'),
        ),
        migrations.AddField(
            model_name='task',
            name='workers',
            field=models.ManyToManyField(blank=True, null=True, related_name='task_workers', to='account.Account'),
        ),
        migrations.AddField(
            model_name='taskreport',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskreport',
            name='resource',
            field=models.ManyToManyField(blank=True, null=True, related_name='task_report_resources', to='resources.ResourcesMeta'),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_author', to='account.Account'),
        ),
        migrations.AlterField(
            model_name='task',
            name='config',
            field=models.TextField(default='{"publish_end_time": 0, "publish_start_time": 0, "implement": {"staged": 0, "stage": {"describe": "", "stage_end_time": 0, "stage_start_time": 0, "title": ""}}}'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='resource',
        ),
        migrations.AddField(
            model_name='task',
            name='resource',
            field=models.ManyToManyField(blank=True, null=True, related_name='task_resources', to='resources.ResourcesMeta'),
        ),
    ]
