# Generated by Django 2.1.2 on 2019-08-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_auto_20190801_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='development_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='task',
            name='publish_end_time',
            field=models.FloatField(default=0.0),
        ),
    ]
