# Generated by Django 2.0.2 on 2019-07-11 02:11

import common.core.dao.time_stamp
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(0, '成员'), (99, '队长')], default=0)),
                ('free', models.BooleanField(default=True)),
                ('create_time', common.core.dao.time_stamp.TimeStampField(default=0)),
                ('update_time', common.core.dao.time_stamp.TimeStampField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
            options={
                'verbose_name': '队伍成员',
                'verbose_name_plural': '队伍成员表',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=140)),
                ('slogan', models.CharField(default='', max_length=255)),
                ('maximum_number', models.PositiveSmallIntegerField(choices=[(10, '一级'), (30, '二级')], default=10)),
                ('full', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, default='', max_length=140)),
                ('public', models.BooleanField(default=False)),
                ('create_time', common.core.dao.time_stamp.TimeStampField(default=0)),
                ('update_time', common.core.dao.time_stamp.TimeStampField(default=0)),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_leader', to='account.Account')),
            ],
            options={
                'verbose_name': '队伍',
                'verbose_name_plural': '队伍表',
            },
        ),
        migrations.AddField(
            model_name='accountteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
    ]
