# Generated by Django 2.1.2 on 2019-07-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='maximum_number',
            field=models.PositiveSmallIntegerField(choices=[(10, '一级 10人'), (30, '二级 30人')], default=10),
        ),
    ]
