
# 登陆session
FIREAUTHSESSION = 'FIRE_SESSION_ID'
# 登陆信号
FIREAUTHSIGN = 'FIRE_AUTH_SIGN'
# session数据库
SESSION_DATABASES = 0
# session时长
SESSION_EFFECTIVE_TIME = 43200
# cookie时长
COOKIE_EFFECTIVE_TIME = 43200

# 任务发布最长等待时间
TASK_PUBLIC_WAIT_TIME = 2592000