# Generated by Django 2.1.2 on 2019-11-06 00:54

import common.core.dao.time_stamp
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceUAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('sex', models.PositiveSmallIntegerField(choices=[(0, '未知'), (1, '男生'), (2, '女生')], default=0)),
                ('password', models.CharField(max_length=255)),
                ('nickname', models.CharField(default='', max_length=50)),
                ('role', models.PositiveSmallIntegerField(choices=[(0, '用户'), (99, '系统管理员')], default=0)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('phone_validated', models.BooleanField(default=False)),
                ('avator', models.CharField(blank=True, default='', max_length=200)),
                ('motto', models.CharField(blank=True, default='', max_length=60)),
                ('create_time', common.core.dao.time_stamp.TimeStampField(default=0)),
                ('update_time', common.core.dao.time_stamp.TimeStampField(default=0)),
                ('options', models.TextField(default='{}')),
                ('temp_access_token', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '脸你主账户表',
                'verbose_name': '脸你主账户',
            },
        ),
    ]
