# Generated by Django 2.1.2 on 2019-11-06 02:03

import common.core.dao.time_stamp
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faceU', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceUDistinguishRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(verbose_name='')),
                ('create_time', common.core.dao.time_stamp.TimeStampField(default=0)),
                ('update_time', common.core.dao.time_stamp.TimeStampField(default=0)),
            ],
            options={
                'verbose_name_plural': '脸你识别记录表',
                'verbose_name': '脸你识别记录',
            },
        ),
        migrations.CreateModel(
            name='FaceUFacialMakeup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_uuid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=125)),
                ('code', models.CharField(blank=True, max_length=125, null=True)),
                ('id_code', models.CharField(blank=True, max_length=30, null=True)),
                ('sex', models.PositiveSmallIntegerField(blank=True, choices=[(0, '未知'), (1, '男生'), (2, '女生')], default=0, null=True)),
                ('create_time', common.core.dao.time_stamp.TimeStampField(default=0)),
                ('update_time', common.core.dao.time_stamp.TimeStampField(default=0)),
            ],
            options={
                'verbose_name_plural': '脸你脸谱表',
                'verbose_name': '脸你脸谱映射',
            },
        ),
        migrations.CreateModel(
            name='FaceUGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('create_time', common.core.dao.time_stamp.TimeStampField(default=0)),
                ('update_time', common.core.dao.time_stamp.TimeStampField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faceU.FaceUAccount')),
                ('member', models.ManyToManyField(blank=True, related_name='faceugroups_member', to='faceU.FaceUFacialMakeup')),
            ],
            options={
                'verbose_name_plural': '脸你分组表',
                'verbose_name': '脸你分组',
            },
        ),
        migrations.AddField(
            model_name='faceudistinguishrecord',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faceU.FaceUGroups'),
        ),
    ]
