# Generated by Django 2.1.2 on 2019-11-09 02:27

import common.core.dao.time_stamp
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faceU', '0002_auto_20191106_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceUFacialMakeupMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('code', models.CharField(blank=True, max_length=125, null=True)),
                ('create_time', common.core.dao.time_stamp.TimeStampField(default=0)),
                ('update_time', common.core.dao.time_stamp.TimeStampField(default=0)),
            ],
            options={
                'verbose_name_plural': '脸你脸谱分组映射表',
                'verbose_name': '脸你脸谱分组映射',
            },
        ),
        migrations.AlterModelOptions(
            name='faceufacialmakeup',
            options={'verbose_name': '脸你脸谱', 'verbose_name_plural': '脸你脸谱表'},
        ),
        migrations.RemoveField(
            model_name='faceufacialmakeup',
            name='code',
        ),
        migrations.RemoveField(
            model_name='faceugroups',
            name='member',
        ),
        migrations.AddField(
            model_name='faceufacialmakeupmapping',
            name='face',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faceU.FaceUFacialMakeup'),
        ),
        migrations.AddField(
            model_name='faceufacialmakeupmapping',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faceU.FaceUGroups'),
        ),
    ]
