# Generated by Django 2.1.2 on 2019-11-14 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faceU', '0003_auto_20191109_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceudistinguishrecord',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faceU.FaceUAccount'),
        ),
    ]
