# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faceRecognition.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='faceRecognition.proto',
  package='faceRecognition',
  syntax='proto3',
  serialized_options=_b('\n\020io.grpc.examples'),
  serialized_pb=_b('\n\x15\x66\x61\x63\x65Recognition.proto\x12\x0f\x66\x61\x63\x65Recognition\"\x15\n\x04\x41uth\x12\r\n\x05token\x18\x05 \x01(\t\"L\n\x08\x66\x61\x63\x65\x44\x61ta\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12#\n\x04\x61uth\x18\x06 \x01(\x0b\x32\x15.faceRecognition.Auth\"T\n\x0b\x66\x61\x63\x65Message\x12\r\n\x05image\x18\x03 \x01(\x0c\x12\x11\n\tface_list\x18\x04 \x01(\t\x12#\n\x04\x61uth\x18\x07 \x01(\x0b\x32\x15.faceRecognition.Auth2\xef\x01\n\x0f\x46\x61\x63\x65Recognition\x12H\n\x0eupdate_library\x12\x19.faceRecognition.faceData\x1a\x19.faceRecognition.faceData\"\x00\x12\x45\n\x0bupload_face\x12\x19.faceRecognition.faceData\x1a\x19.faceRecognition.faceData\"\x00\x12K\n\x0brecognition\x12\x1c.faceRecognition.faceMessage\x1a\x1c.faceRecognition.faceMessage\"\x00\x42\x12\n\x10io.grpc.examplesb\x06proto3')
)




_AUTH = _descriptor.Descriptor(
  name='Auth',
  full_name='faceRecognition.Auth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='faceRecognition.Auth.token', index=0,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=63,
)


_FACEDATA = _descriptor.Descriptor(
  name='faceData',
  full_name='faceRecognition.faceData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='faceRecognition.faceData.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='faceRecognition.faceData.uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auth', full_name='faceRecognition.faceData.auth', index=2,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=141,
)


_FACEMESSAGE = _descriptor.Descriptor(
  name='faceMessage',
  full_name='faceRecognition.faceMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='faceRecognition.faceMessage.image', index=0,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='face_list', full_name='faceRecognition.faceMessage.face_list', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auth', full_name='faceRecognition.faceMessage.auth', index=2,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=227,
)

_FACEDATA.fields_by_name['auth'].message_type = _AUTH
_FACEMESSAGE.fields_by_name['auth'].message_type = _AUTH
DESCRIPTOR.message_types_by_name['Auth'] = _AUTH
DESCRIPTOR.message_types_by_name['faceData'] = _FACEDATA
DESCRIPTOR.message_types_by_name['faceMessage'] = _FACEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Auth = _reflection.GeneratedProtocolMessageType('Auth', (_message.Message,), {
  'DESCRIPTOR' : _AUTH,
  '__module__' : 'faceRecognition_pb2'
  # @@protoc_insertion_point(class_scope:faceRecognition.Auth)
  })
_sym_db.RegisterMessage(Auth)

faceData = _reflection.GeneratedProtocolMessageType('faceData', (_message.Message,), {
  'DESCRIPTOR' : _FACEDATA,
  '__module__' : 'faceRecognition_pb2'
  # @@protoc_insertion_point(class_scope:faceRecognition.faceData)
  })
_sym_db.RegisterMessage(faceData)

faceMessage = _reflection.GeneratedProtocolMessageType('faceMessage', (_message.Message,), {
  'DESCRIPTOR' : _FACEMESSAGE,
  '__module__' : 'faceRecognition_pb2'
  # @@protoc_insertion_point(class_scope:faceRecognition.faceMessage)
  })
_sym_db.RegisterMessage(faceMessage)


DESCRIPTOR._options = None

_FACERECOGNITION = _descriptor.ServiceDescriptor(
  name='FaceRecognition',
  full_name='faceRecognition.FaceRecognition',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=230,
  serialized_end=469,
  methods=[
  _descriptor.MethodDescriptor(
    name='update_library',
    full_name='faceRecognition.FaceRecognition.update_library',
    index=0,
    containing_service=None,
    input_type=_FACEDATA,
    output_type=_FACEDATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='upload_face',
    full_name='faceRecognition.FaceRecognition.upload_face',
    index=1,
    containing_service=None,
    input_type=_FACEDATA,
    output_type=_FACEDATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='recognition',
    full_name='faceRecognition.FaceRecognition.recognition',
    index=2,
    containing_service=None,
    input_type=_FACEMESSAGE,
    output_type=_FACEMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACERECOGNITION)

DESCRIPTOR.services_by_name['FaceRecognition'] = _FACERECOGNITION

# @@protoc_insertion_point(module_scope)
