# Generated by Django 2.1.2 on 2019-08-01 10:40

import common.core.dao.time_stamp
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('account', '0002_account_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountExhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(default='')),
                ('show', models.BooleanField(default=True)),
                ('create_time', common.core.dao.time_stamp.TimeStampField(default=0)),
                ('update_time', common.core.dao.time_stamp.TimeStampField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
                ('resource', models.ManyToManyField(blank=True, null=True, related_name='account_exhibition_resources', to='resources.ResourcesMeta')),
            ],
            options={
                'verbose_name_plural': '用户作品展示表',
                'verbose_name': '用户作品展示',
            },
        ),
    ]
