apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fire-hydrant-redis-cluster-deloyment1
  namespace: fire-hydrant
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fire-hydrant-redis-cluster1
    spec:
      volumes:
      - name: cluster1
        hostPath:
          path: {{ .Values.FIRE_HYDRANT_REDIS_CLUSTER_WORK_DIR }}/7001/data
      containers:
      - name: redis-cluster1
        image: docker.dev.shoogoome.com/firehydrant/redis-cluster:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7001
        - containerPort: 17001
        volumeMounts:
        - name: cluster1
          mountPath: /data
        env:
        - name: REDIS_PORT
          value: "7001"
---
apiVersion: v1
kind: Service
metadata:
  name: fire-hydrant-redis-cluster-service1
  namespace: fire-hydrant
spec:
  selector:
    app: fire-hydrant-redis-cluster1
  ports:
  - port: 7001
    targetPort: 7001
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fire-hydrant-redis-cluster-deloyment2
  namespace: fire-hydrant
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fire-hydrant-redis-cluster2
    spec:
      volumes:
      - name: cluster2
        hostPath:
          path: {{ .Values.FIRE_HYDRANT_REDIS_CLUSTER_WORK_DIR }}/7002/data
      containers:
      - name: redis-cluster2
        image: docker.dev.shoogoome.com/firehydrant/redis-cluster:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7002
        - containerPort: 17002
        volumeMounts:
        - name: cluster2
          mountPath: /data
        env:
        - name: REDIS_PORT
          value: "7002"
---
apiVersion: v1
kind: Service
metadata:
  name: fire-hydrant-redis-cluster-service2
  namespace: fire-hydrant
spec:
  selector:
    app: fire-hydrant-redis-cluster1
  ports:
  - port: 7002
    targetPort: 7002
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fire-hydrant-redis-cluster-deloyment3
  namespace: fire-hydrant
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fire-hydrant-redis-cluster3
    spec:
      volumes:
      - name: cluster3
        hostPath:
          path: {{ .Values.FIRE_HYDRANT_REDIS_CLUSTER_WORK_DIR }}/7003/data
      containers:
      - name: redis-cluster3
        image: docker.dev.shoogoome.com/firehydrant/redis-cluster:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7003
        - containerPort: 17003
        volumeMounts:
        - name: cluster3
          mountPath: /data
        env:
        - name: REDIS_PORT
          value: "7003"
---
apiVersion: v1
kind: Service
metadata:
  name: fire-hydrant-redis-cluster-service3
  namespace: fire-hydrant
spec:
  selector:
    app: fire-hydrant-redis-cluster3
  ports:
  - port: 7003
    targetPort: 7003
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fire-hydrant-redis-cluster-deloyment4
  namespace: fire-hydrant
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fire-hydrant-redis-cluster4
    spec:
      volumes:
      - name: cluster4
        hostPath:
          path: {{ .Values.FIRE_HYDRANT_REDIS_CLUSTER_WORK_DIR }}/7004/data
      containers:
      - name: redis-cluster4
        image: docker.dev.shoogoome.com/firehydrant/redis-cluster:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7004
        - containerPort: 17004
        volumeMounts:
        - name: cluster4
          mountPath: /data
        env:
        - name: REDIS_PORT
          value: "7004"
---
apiVersion: v1
kind: Service
metadata:
  name: fire-hydrant-redis-cluster-service4
  namespace: fire-hydrant
spec:
  selector:
    app: fire-hydrant-redis-cluster4
  ports:
  - port: 7004
    targetPort: 7004
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fire-hydrant-redis-cluster-deloyment5
  namespace: fire-hydrant
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fire-hydrant-redis-cluster5
    spec:
      volumes:
      - name: cluster5
        hostPath:
          path: {{ .Values.FIRE_HYDRANT_REDIS_CLUSTER_WORK_DIR }}/7005/data
      containers:
      - name: redis-cluster5
        image: docker.dev.shoogoome.com/firehydrant/redis-cluster:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7005
        - containerPort: 17005
        volumeMounts:
        - name: cluster5
          mountPath: /data
        env:
        - name: REDIS_PORT
          value: "7005"
---
apiVersion: v1
kind: Service
metadata:
  name: fire-hydrant-redis-cluster-service5
  namespace: fire-hydrant
spec:
  selector:
    app: fire-hydrant-redis-cluster5
  ports:
  - port: 7005
    targetPort: 7005
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fire-hydrant-redis-cluster-deloyment6
  namespace: fire-hydrant
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fire-hydrant-redis-cluster6
    spec:
      volumes:
      - name: cluster6
        hostPath:
          path: {{ .Values.FIRE_HYDRANT_REDIS_CLUSTER_WORK_DIR }}/7006/data
      containers:
      - name: redis-cluster6
        image: docker.dev.shoogoome.com/firehydrant/redis-cluster:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7006
        - containerPort: 17006
        volumeMounts:
        - name: cluster6
          mountPath: /data
        env:
        - name: REDIS_PORT
          value: "7006"
---
apiVersion: v1
kind: Service
metadata:
  name: fire-hydrant-redis-cluster-service6
  namespace: fire-hydrant
spec:
  selector:
    app: fire-hydrant-redis-cluster6
  ports:
  - port: 7006
    targetPort: 7006
---



