# Generated by Django 2.0.2 on 2019-07-14 08:09

import common.core.dao.time_stamp
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.TextField(default='{"alipay": ""}')),
                ('total_amount', models.FloatField(default=0.0)),
                ('available_amount', models.FloatField(default=0.0)),
                ('create_time', common.core.dao.time_stamp.TimeStampField(default=0)),
                ('update_time', common.core.dao.time_stamp.TimeStampField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
            options={
                'verbose_name': '支付虚拟账户',
                'verbose_name_plural': '支付虚拟账户表',
            },
        ),
        migrations.CreateModel(
            name='PayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.PositiveSmallIntegerField(choices=[(0, '转入'), (1, '转出'), (2, '转账')], default=0)),
                ('amount', models.FloatField(default=0.0)),
                ('create_time', common.core.dao.time_stamp.TimeStampField(default=0)),
                ('update_time', common.core.dao.time_stamp.TimeStampField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_record_account', to='account.Account')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_record_target', to='account.Account')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录表',
            },
        ),
    ]
