# Generated by Django 2.1.2 on 2019-10-10 01:36

import common.core.dao.time_stamp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20191008_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practiceattendance',
            name='state',
        ),
        migrations.AddField(
            model_name='practiceattendance',
            name='absent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practiceattendance',
            name='late',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practiceattendance',
            name='leaver',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practicetag',
            name='create_time',
            field=common.core.dao.time_stamp.TimeStampField(default=0),
        ),
        migrations.AddField(
            model_name='practicetag',
            name='update_time',
            field=common.core.dao.time_stamp.TimeStampField(default=0),
        ),
    ]
