# Generated by Django 2.1.2 on 2019-10-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_auto_20191010_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicearrangement',
            name='end_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='practicearrangement',
            name='start_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
